### ISSUE TITLE
Error on windows

### ISSUE THREAD

**Issue by ahmetuygun** [jesperancinha/sea-shell-archiver#14]
Hi @jesperancinha,  thank you for great writing and example. could you add a detailed instruction to install and run in windows. because I'm getting some error about maven plugin or version of java, although  i tried in different java version.  

`By default, the Java language level is set to 5 which is not supported by the current Java version. Update the language level to 6+.Update source level in sea-shell-soap-service`

**Comment by jesperancinha** [comment]
Hi @ahmetuygun. Your comment came at the same time I was doing an update to the project. During this update, I tested the import of the project on Windows. I do know the issue you mention and that could have happened if for some reason the maven plugin wasn't correctly configured or if maven wasn't able to find the configured java version. It does default to Java 5 in these cases. The soap service and all clients have been updated according to some spring tutorials I found from Pivotal. This is all explained in the Readme.md files of the project. Please let me know if you run into any issue further with the latest updated
